backend:
  deployment:
    replicas: 1
    repository: ""
    tag: "1.0.3"
    resources:
      requests:
        cpu: 500m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 256Mi
  service:
    port: 8000
  baseurl: ""
frontend:
  deployment:
    replicas: 1
    repository: ""
    tag: "1.0.1"
    resources:
      requests:
        cpu: 500m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 256Mi
  service:
    port: 80
  baseurl: ""
