apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: {{ .Value.frontend.deployment.replicas}}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Value.frontend.deployment.repository}}:{{ .Value.frontend.deployment.tag}}
        ports:
        - containerPort: 80
        env:
        - configMapRef:
            name: frontend-config
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          {{- toYaml .Values.frontend.deployment.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  ports:
  - port: {{ .Value.frontend.service.port}}
    targetPort: 80
    protocol: TCP
  selector:
    app: frontend
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  data:
    REACT_APP_API_BASE_URL: {{ .Value.frontend.baseurl}}