apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: {{ .Values.frontend.deployment.replicas}}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.deployment.repository}}:{{ .Values.frontend.deployment.tag}}"
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_BASE_URL
          value: {{ .Values.frontend.baseurl | default "http://backend.example.com" }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          {{- toYaml .Values.frontend.deployment.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.frontend.service.port}}
    targetPort: 80
    protocol: TCP
  selector:
    app: frontend